### ISSUE TITLE
Choose a open source license

### ISSUE THREAD

**Issue by TiagoGouvea** [TiagoGouvea/open-source-event-management#7]
We need choose for a license... I'm not so good on it, but I think:
- The code is open source, then, everyone can get it and change
- If someone what to create a business using that code, no problem

Some questions:

? When the projects must have reference to the main project?

What more to think about?

**Comment by gugadmin** [comment]
Hi, this is a great guide:

http://choosealicense.com/

I recommend MIT for your purposes.

**Comment by davidvavra** [comment]
Hi, this is a great guide:

http://choosealicense.com/

I recommend MIT for your purposes.

**Comment by mrprompt** [comment]
MIT  :+1:

**Comment by abdala** [comment]
MIT

**Comment by TiagoGouvea** [comment]
Ok. MIT! :+1:
